## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux

julia:
  - 1.2
  - 1.3

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy

notifications:
  email: false

before_script:
  - julia -e 'using Pkg; pkg"precompile"'
